### ISSUE TITLE
Need new features

### ISSUE THREAD

**Issue by CodingAviator** [Epicalable/JARVIS#2]
We need to add new features like APIs, improve upon the Jarintent dataset and also start working on making JARVIS talk.

**Comment by Mahadhevha** [comment]
We are looking for new features to add examples of what we planned is to have a mapapi for map images and soon search results from multiple websites.
Making Jarvis to talk might need time to develope as we need to enhance the wording engine to just feed the voicer to say what goes through it instead of adding talking lines to every output sentence in the code boss.

**Comment by Mahadhevha** [comment]
Due to other important improvements and fixes we are pushing the improvements for the future of JARVIS to a later date.
