### ISSUE TITLE
Bringing Back Stock Price Retrieving Through The Gui.

### ISSUE THREAD

**Issue by CodingAviator** [Epicalable/JARVIS#4]
It was possible to retrieve stock prices before and now it has been removed due to an error.
This request is to bring it back and also improve the documentation by explaining to users about the Jaraudit Text File.

**Comment by Mahadhevha** [comment]
We have brought back the stock retrieval features in commit 88626d66e. But it can only retrieve how much the stock have changed since the previous day.
Ex. AAPL Stock change is +0.43
Rather than AAPL Stock price is 334.50 usd

We will be continuing to work on this issue and any help will be appreciated.

This problem is towards Web scraping and apis and not related to the gui or layout side of JARVIS.

**Comment by Mahadhevha** [comment]
We have also improved the documentation(README.md) to include the importance and uses of Jar-Audit file in the commit 88626d66e for the users to understand.

**Comment by CodingAviator** [comment]
Thank you for your time and dedication to fix this errors and help to improve user understandability.
We will continue to work on bringing back the legacy stock retrieval program.

**Comment by Mahadhevha** [comment]
IT'S A WRAP!!!
As of the latest commit 0c6d067 We have successfully integrated the ability to fetch current stock prices into JARVIS.
All it took was for us to learn some web-scraping online.

**Comment by CodingAviator** [comment]
Thank you @MahaMohan for taking your time to finish this issue.
With this commit this issue will be archived.
Thanks team
